k add volume 5
j add volume -5
h seek -5
l seek 5
H add chapter -1
L add chapter 1
ctrl+u show-text "${metadata/by-key/comment}" 5000
ctrl+U run sh -c "xdg-open \"$1\"" _ "${metadata/by-key/comment}"
