script-opts=ytdl_hook-ytdl_path=yt-dlp
ytdl-format=bestvideo[vcodec!^=av01]+bestaudio/best
sub-auto=fuzzy
# sub-font="fontName"
sub-bold=yes
slang=en,eng
sid=auto
sub-font-size=40
sub-border-size=2

# playback
save-position-on-quit=yes
keep-open=yes
hwdec=nvdec
vo=gpu
video-sync=display-resample
osd-duration=2000
